function [bad_channels, magnitude, channel, shank]=ReadImpedanceTestXML(chanMapFile)
%reads impedance test xml file generated by open ephys, for use with silicon
%probes to check for bad channels. %mw 3.17.2025
%at the moment it just reads the first '*.xml' file found in the current
%directory. We could upgrade it to find the
%most recent relevant impedance file, either automatically or manually.
%Note that we have to correct the channel numbers in the xml file according to the
% channel map file chanMap128.mat.
%
%usage:
%  [bad_channels, magnitude, channel, shank]=ReadImpedanceTestXML(chanMapFile)
%  chanMapFile: full path to chanMap128.mat. Optional -- callers that
%  already know the location should pass it explicitly (e.g. PlotTC_LFP2
%  passes out.channelmap_file, which ProcessTC_LFP2 already resolved and
%  saved). If omitted, falls back to checking a couple of known/likely
%  locations, see below.
%
%  looks in current directory and loads the first xml file it finds
%-mike/claude 9.1.26: now accepts chanMapFile as an argument instead of
%guessing via a chain of hardcoded/relative paths.
bad_channels=[];

d=dir('*.xml');
if isempty(d) fprintf('\n%s: could not find impedance test file', mfilename), return, end

if nargin==0 || isempty(chanMapFile)
    %no location supplied -- fall back to known/likely locations.
    %1) the primary user's rig computer keeps a copy here:
    hardcoded_path='C:\Users\wehrlab\Desktop\Stuff\chanMap128.mat';
    %2) otherwise, derive DataRoot from the file hierarchy: this function
    %is expected to be run from the EphysPath directory (where outLFP.mat
    %lives), which is 2 dirs below DataRoot (DataRoot/BonsaiFolder/EphysPath,
    %BonsaiFolder being where StartAcquisitionSec.mat lives, i.e. 1 dir
    %below DataRoot).
    DataRoot=fullfile(pwd, '..', '..');
    derived_path=fullfile(DataRoot, 'chanMap128.mat');
    if exist(hardcoded_path, 'file')
        chanMapFile=hardcoded_path;
    elseif exist(derived_path, 'file')
        chanMapFile=derived_path;
    else
        error(sprintf(['ReadImpedanceTestXML: could not find chanMap128.mat. Tried:\n  %s\n  %s\n', ...
            'Pass its location explicitly as an argument instead.'], hardcoded_path, derived_path))
    end
end

load(chanMapFile)

%here you could find the most recent file relative to youre recording session using d.date
filename=d(1).name;
s=xml2struct(filename);

chan=0;
for sh=1:2
    for ch=1:64
        chan=chan+1;
        shank(chan)=sh;
        channel(chan)=chan;
        magnitude(chan)=str2num(s.IMPEDANCES.HEADSTAGE{sh}.CHANNEL{ch}.Attributes.magnitude);
        name{chan}=s.IMPEDANCES.HEADSTAGE{sh}.CHANNEL{ch}.Attributes.name;
        number(chan)=str2num(s.IMPEDANCES.HEADSTAGE{sh}.CHANNEL{ch}.Attributes.number);
        phase(chan)=str2num(s.IMPEDANCES.HEADSTAGE{sh}.CHANNEL{ch}.Attributes.phase);
    end

end

bad_chan_thresh=2*std(magnitude);
bad_chan_thresh=1e6; %1 MOhm
bad_channels=sort(chanMap(find(magnitude>bad_chan_thresh)));

figure
subplot(211)
stem(chanMap, magnitude)
set(gca, 'yscale', 'log')
ylabel('magnitude (Ohms)')
line(xlim, [1 1]*bad_chan_thresh)
title(['impedance from file ', filename])
text(chanMap, magnitude, int2str(chanMap'))

subplot(212)
stem(chanMap, phase)
ylabel('phase')
xlabel('channel')
text(chanMap, phase, int2str(chanMap'))
set(gcf, 'pos',[192 418 1640 420]);%192 818 2140 420

fprintf('\n%s: ', mfilename)
fprintf('\nreading file %s from %s', filename, d(1).date)
fprintf('\nusing channel map %s', chanMapFile)
fprintf('\nusing magnitude threshold of %.1f MOhm', bad_chan_thresh/1e6)
fprintf('\ndetected bad channels: ')
fprintf('%d ', bad_channels)

